packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '0': '@nestjs/core'
  '1': '@prisma/client'
  '2': '@prisma/engines'
  '3': prisma
  '4': unrs-resolver
  '5': bcrypt
  '6': puppeteer
  '7': canvas
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  prisma: true
  sharp: true
  unrs-resolver: true
