export type PhaseType = 'PLAN' | 'DO' | 'CHECK' | 'ACT';
export type ToolDifficulty = 'beginner' | 'intermediate' | 'advanced';

export type ToolType =
  | 'SIPOC' | 'VOC' | 'CTQ' | 'PROJECT_CHARTER' | 'SWOT' | 'GUT'
  | 'PARETO' | 'ISHIKAWA' | 'FIVE_WHYS' | 'FLOWCHART' | 'VSM' | 'FIVE_W2H'
  | 'BENCHMARKING' | 'KANO' | 'FMEA' | 'BRAINSTORMING' | 'CAUSE_EFFECT_MATRIX' | 'PROCESS_MAP'
  | 'KANBAN' | 'ACTION_PLAN' | 'CHECKLIST' | 'KPI_DASHBOARD'
  | 'SPC_CHART' | 'HISTOGRAM' | 'RUN_CHART' | 'BEFORE_AFTER'
  | 'STANDARDIZATION' | 'AUDIT' | 'LESSONS_LEARNED' | 'SOP' | 'TRAINING';

export interface ToolMetadata {
  name: string;
  phase: PhaseType;
  description: string;
  objective: string;
  whenToUse: string[];
  whenToAvoid: string[];
  benefits: string[];
  estimatedDuration: string;
  difficulty: ToolDifficulty;
  relatedTools: ToolType[];
  icon: string;
  stepByStep: string[];
  commonErrors: string[];
  bestPractices: string[];
  exampleContext: string;
}

export const TOOL_METADATA: Record<ToolType, ToolMetadata> = {
  FIVE_WHYS: {
    name: '5 Porquês',
    phase: 'PLAN',
    description: 'Técnica iterativa para identificar a causa raiz de um problema perguntando "Por quê?" repetidamente.',
    objective: 'Chegar à causa raiz de um problema através de análise sequencial.',
    whenToUse: [
      'Quando o problema é simples ou moderadamente complexo',
      'Quando existe uma cadeia causal clara',
      'Para análise rápida de causa raiz',
      'Como complemento ao Diagrama de Ishikawa',
    ],
    whenToAvoid: [
      'Problemas com múltiplas causas raiz independentes',
      'Sistemas altamente complexos e interconectados',
      'Quando os dados disponíveis são insuficientes',
    ],
    benefits: [
      'Simples de aplicar, não requer ferramentas especiais',
      'Vai além dos sintomas superficiais',
      'Facilita o entendimento compartilhado da equipe',
      'Direciona ações corretivas na causa, não no sintoma',
    ],
    estimatedDuration: '30–60 min',
    difficulty: 'beginner',
    relatedTools: ['ISHIKAWA', 'PARETO', 'FMEA'],
    icon: 'help-circle',
    stepByStep: [
      'Defina claramente o problema (efeito observado)',
      'Pergunte "Por quê isso ocorre?" e registre a resposta',
      'Para cada resposta, pergunte "Por quê?" novamente',
      'Repita até 5 vezes ou até chegar à causa raiz',
      'Valide a causa raiz com dados ou evidências',
      'Defina ações corretivas na causa raiz identificada',
    ],
    commonErrors: [
      'Parar cedo (na 1ª ou 2ª iteração) — geralmente são sintomas',
      'Propor soluções antes de confirmar a causa raiz',
      'Realizar a análise sozinho sem envolver a equipe operacional',
      'Aceitar respostas vagas como "falta de treinamento" sem aprofundar',
    ],
    bestPractices: [
      'Envolva quem executa o processo — eles conhecem as causas reais',
      'Baseie cada resposta em evidências, não em opiniões',
      'É normal ter mais de 5 porquês — vá até a causa raiz',
      'Combine com Ishikawa para problemas com múltiplas dimensões',
    ],
    exampleContext: 'Problema: Atraso nas entregas. Por quê? → Veículos saem atrasados. Por quê? → Carregamento demora. Por quê? → Separação de pedidos incorreta. Por quê? → Sistema de picking manual. Por quê? → Não há automação no WMS. Causa raiz: ausência de automação no processo de picking.',
  },

  ISHIKAWA: {
    name: 'Diagrama de Ishikawa',
    phase: 'PLAN',
    description: 'Diagrama de espinha de peixe que organiza causas potenciais de um problema em categorias (6M).',
    objective: 'Mapear e categorizar todas as causas potenciais de um problema para priorização.',
    whenToUse: [
      'Problemas com múltiplas causas potenciais',
      'Análise de falhas em processos industriais',
      'Sessões de brainstorming estruturado com equipe',
      'Quando precisa comunicar causas de forma visual',
    ],
    whenToAvoid: [
      'Problemas com causa raiz única e óbvia',
      'Quando o tempo disponível é muito curto',
      'Sem participação da equipe que conhece o processo',
    ],
    benefits: [
      'Visualização clara das relações causa-efeito',
      'Estimula participação de toda a equipe',
      'Previne foco prematuro em uma única causa',
      'Documenta o conhecimento da equipe',
    ],
    estimatedDuration: '1–2 horas',
    difficulty: 'beginner',
    relatedTools: ['FIVE_WHYS', 'PARETO', 'BRAINSTORMING'],
    icon: 'git-branch',
    stepByStep: [
      'Defina o efeito (problema) e escreva à direita da espinha',
      'Desenhe as espinhas principais: Máquina, Método, Material, Mão-de-obra, Medição, Meio Ambiente',
      'Para cada categoria, liste causas potenciais',
      'Aprofunde cada causa com sub-causas (ramificações)',
      'Priorize as causas mais prováveis com dados',
      'Valide com o time operacional',
    ],
    commonErrors: [
      'Listar soluções em vez de causas',
      'Não aprofundar as causas em sub-causas',
      'Ignorar categorias com menos causas óbvias',
      'Não validar as causas com dados reais',
    ],
    bestPractices: [
      'Use os 6M como ponto de partida, adapte se necessário',
      'Envolva operadores, técnicos e gestores',
      'Combine com 5 Porquês para aprofundar cada causa',
      'Fotografe o resultado para documentação',
    ],
    exampleContext: 'Problema: Alto índice de retrabalho na linha de montagem. Causas por categoria: Máquina (calibração irregular), Método (sem procedimento padrão), Material (variação de fornecedor), Mão-de-obra (falta de treinamento), Medição (gabarito desatualizado), Meio Ambiente (temperatura da sala fora do especificado).',
  },

  GUT: {
    name: 'Matriz GUT',
    phase: 'PLAN',
    description: 'Matriz de priorização de problemas com base em Gravidade, Urgência e Tendência.',
    objective: 'Priorizar problemas ou causas para focar esforços nos de maior impacto.',
    whenToUse: [
      'Quando há múltiplos problemas ou causas a priorizar',
      'Para alinhar a equipe sobre o que atacar primeiro',
      'No início de um projeto para selecionar o problema principal',
    ],
    whenToAvoid: [
      'Quando o problema prioritário já é claro para todos',
      'Se não há dados suficientes para avaliar os critérios',
    ],
    benefits: [
      'Critério objetivo e quantitativo de priorização',
      'Facilita consenso da equipe',
      'Simples e rápido de aplicar',
    ],
    estimatedDuration: '30–45 min',
    difficulty: 'beginner',
    relatedTools: ['ISHIKAWA', 'PARETO', 'FIVE_WHYS'],
    icon: 'sliders',
    stepByStep: [
      'Liste todos os problemas ou causas a analisar',
      'Para cada item, atribua nota de 1–5 para Gravidade (impacto se nada feito)',
      'Atribua nota de 1–5 para Urgência (pressão do tempo)',
      'Atribua nota de 1–5 para Tendência (vai piorar?)',
      'Calcule GUT = G × U × T',
      'Ordene por pontuação — o maior score é a prioridade #1',
    ],
    commonErrors: [
      'Avaliar por intuição sem discussão com a equipe',
      'Notas inconsistentes entre avaliadores — use consenso',
      'Ignorar itens com score alto em apenas um critério',
    ],
    bestPractices: [
      'Avalie com toda a equipe para evitar viés individual',
      'Use evidências e dados para justificar as notas',
      'Reavalie periodicamente conforme o projeto avança',
    ],
    exampleContext: 'Problemas: Atraso nas entregas (G=5, U=5, T=4 → 100), Retrabalho na linha (G=4, U=3, T=5 → 60), Custo de estoque alto (G=3, U=2, T=3 → 18). Prioridade: atrasos nas entregas.',
  },

  SWOT: {
    name: 'Análise SWOT',
    phase: 'PLAN',
    description: 'Análise de Forças, Fraquezas, Oportunidades e Ameaças do projeto ou processo.',
    objective: 'Mapear fatores internos e externos que influenciam o sucesso do projeto.',
    whenToUse: [
      'No início do projeto para contextualização estratégica',
      'Para avaliar viabilidade de uma solução',
      'Quando há incerteza sobre o contexto organizacional',
    ],
    whenToAvoid: [
      'Projetos operacionais de curto prazo sem componente estratégico',
      'Quando os fatores já são conhecidos e documentados',
    ],
    benefits: [
      'Visão 360° do ambiente do projeto',
      'Identifica riscos e oportunidades antecipadamente',
      'Facilita alinhamento com sponsors e liderança',
    ],
    estimatedDuration: '45–90 min',
    difficulty: 'beginner',
    relatedTools: ['PROJECT_CHARTER', 'FMEA'],
    icon: 'layout-grid',
    stepByStep: [
      'Reúna stakeholders do projeto',
      'Liste Forças: vantagens internas do time/processo',
      'Liste Fraquezas: limitações internas',
      'Liste Oportunidades: fatores externos favoráveis',
      'Liste Ameaças: fatores externos desfavoráveis',
      'Defina estratégias: SO (usar forças para aproveitar oportunidades), ST, WO, WT',
    ],
    commonErrors: [
      'Confundir fraquezas com ameaças (interno vs. externo)',
      'Listar itens genéricos demais',
      'Não transformar a análise em ações concretas',
    ],
    bestPractices: [
      'Seja específico — evite generalidades como "equipe capacitada"',
      'Cada item deve ser verificável',
      'Use a SWOT para construir o plano de ação',
    ],
    exampleContext: 'Projeto de redução de lead time. Forças: equipe experiente em Lean. Fraquezas: sistema ERP legado. Oportunidades: novo WMS sendo implementado. Ameaças: sazonalidade de demanda.',
  },

  SIPOC: {
    name: 'SIPOC',
    phase: 'PLAN',
    description: 'Mapa de alto nível do processo: Supplier → Input → Process → Output → Customer.',
    objective: 'Definir os limites do processo e suas principais entradas/saídas antes do mapeamento detalhado.',
    whenToUse: [
      'No início do projeto para definir escopo do processo',
      'Antes de fazer o VSM ou fluxograma detalhado',
      'Para alinhar a equipe sobre o que está no escopo',
    ],
    whenToAvoid: [
      'Processos muito simples com etapas óbvias',
      'Quando o objetivo já é otimizar um subprocesso específico',
    ],
    benefits: [
      'Define claramente os limites do processo',
      'Identifica fornecedores e clientes internos/externos',
      'Alinha a equipe sobre o escopo antes de detalhar',
    ],
    estimatedDuration: '45–60 min',
    difficulty: 'beginner',
    relatedTools: ['VSM', 'FLOWCHART', 'PROJECT_CHARTER'],
    icon: 'arrow-right-circle',
    stepByStep: [
      'Identifique o processo principal (coluna P)',
      'Descreva as etapas principais (3–7 etapas)',
      'Identifique os outputs de cada etapa',
      'Identifique os clientes que recebem os outputs',
      'Identifique os inputs necessários para o processo',
      'Identifique os fornecedores dos inputs',
    ],
    commonErrors: [
      'Detalhar demais — SIPOC é visão de alto nível',
      'Confundir processo com departamento',
      'Esquecer clientes internos',
    ],
    bestPractices: [
      'Construa de dentro para fora: Process → Output → Customer → Input → Supplier',
      'Limite a 5–7 etapas principais',
      'Valide com quem executa o processo',
    ],
    exampleContext: 'Processo de separação de pedidos: S: Fornecedores de material → I: Pedidos, estoque → P: Recebimento, separação, conferência, embalagem, expedição → O: Pedido embalado, nota fiscal → C: Cliente final, transportadora.',
  },

  FIVE_W2H: {
    name: '5W2H',
    phase: 'PLAN',
    description: 'Plano de ação estruturado respondendo What, Why, Where, When, Who, How, How Much.',
    objective: 'Detalhar ações de forma completa e sem ambiguidade.',
    whenToUse: [
      'Para documentar planos de ação de forma padronizada',
      'Quando uma ação precisa ser delegada com clareza',
      'Para garantir que nenhum aspecto da ação seja esquecido',
    ],
    whenToAvoid: [
      'Ações simples e auto-explicativas',
      'Quando o kanban ou task manager já captura esses dados',
    ],
    benefits: [
      'Elimina ambiguidade nas ações',
      'Facilita acompanhamento e cobrança',
      'Força o responsável a pensar em todos os aspectos',
    ],
    estimatedDuration: '15–30 min por ação',
    difficulty: 'beginner',
    relatedTools: ['ACTION_PLAN', 'KANBAN'],
    icon: 'list-checks',
    stepByStep: [
      'What: O que será feito?',
      'Why: Por que é necessário?',
      'Where: Onde será executado?',
      'When: Quando? (prazo)',
      'Who: Quem é o responsável?',
      'How: Como será executado?',
      'How Much: Quanto vai custar?',
    ],
    commonErrors: [
      'Deixar campos em branco',
      'Responsáveis múltiplos sem um responsável principal',
      'Prazos sem data específica ("em breve")',
    ],
    bestPractices: [
      'Um responsável por ação — quem responde pelo resultado',
      'Prazos em datas específicas, não períodos vagos',
      'How Much estimado mesmo que aproximado',
    ],
    exampleContext: 'O quê: Implementar automação de picking. Por quê: Reduzir erros em 80%. Onde: CD São Paulo. Quando: 15/03/2024. Quem: João Silva (TI). Como: Integração WMS com scanner. Quanto: R$ 45.000.',
  },

  PARETO: {
    name: 'Gráfico de Pareto',
    phase: 'PLAN',
    description: 'Gráfico de barras ordenado por frequência com linha cumulativa, baseado no princípio 80/20.',
    objective: 'Identificar as causas/problemas que representam 80% do impacto total.',
    whenToUse: [
      'Quando há dados históricos de ocorrências ou defeitos',
      'Para priorizar onde investir esforço de melhoria',
      'Para comunicar prioridades à liderança com dados',
    ],
    whenToAvoid: [
      'Sem dados históricos suficientes (mínimo 20–30 ocorrências)',
      'Quando todas as categorias têm peso similar',
    ],
    benefits: [
      'Decisão baseada em dados, não em opinião',
      'Foco nos poucos vitais vs. muitos triviais',
      'Comunicação visual clara para liderança',
    ],
    estimatedDuration: '30–60 min (incluindo coleta de dados)',
    difficulty: 'intermediate',
    relatedTools: ['ISHIKAWA', 'GUT', 'SPC_CHART'],
    icon: 'bar-chart-2',
    stepByStep: [
      'Colete dados de ocorrências por categoria (defeito, causa, cliente, etc.)',
      'Calcule frequência e percentual de cada categoria',
      'Ordene da maior para menor frequência',
      'Calcule percentual cumulativo',
      'Plote barras (frequência) e linha (% cumulativo)',
      'Identifique o ponto de 80% na linha cumulativa',
      'As categorias à esquerda desse ponto são as prioritárias',
    ],
    commonErrors: [
      'Não ordenar as barras por frequência',
      'Usar categorias amplas demais (perde o foco)',
      'Ignorar a linha cumulativa — ela é a essência do Pareto',
    ],
    bestPractices: [
      'Colete dados de um período representativo (mínimo 30 dias)',
      'Quebre categorias muito amplas em subcategorias',
      'Refaça o Pareto após melhorias para medir impacto',
    ],
    exampleContext: 'Defeitos em linha de produção: Arranhados (45%), Dimensão fora (25%), Cor incorreta (15%), Embalagem danificada (10%), Outros (5%). Prioridade: arranhados + dimensão = 70% dos defeitos.',
  },

  FMEA: {
    name: 'FMEA',
    phase: 'PLAN',
    description: 'Análise de Modos de Falha e Efeitos — avalia riscos pelo RPN = Severidade × Ocorrência × Detecção.',
    objective: 'Identificar e priorizar falhas potenciais antes que ocorram, prevenindo problemas de qualidade.',
    whenToUse: [
      'Novos produtos ou processos em desenvolvimento',
      'Mudanças em processos existentes',
      'Quando falhas têm impacto crítico em segurança ou qualidade',
      'Auditoria de processos de alto risco',
    ],
    whenToAvoid: [
      'Processos simples com falhas de baixo impacto',
      'Quando o objetivo é corretivo (já ocorreu) — use 5 Porquês',
    ],
    benefits: [
      'Abordagem preventiva — evita falhas antes que ocorram',
      'Priorização quantitativa de riscos pelo RPN',
      'Documenta o conhecimento de riscos da equipe',
      'Base para planos de controle e monitoramento',
    ],
    estimatedDuration: '2–4 horas',
    difficulty: 'advanced',
    relatedTools: ['ISHIKAWA', 'FIVE_WHYS', 'PARETO'],
    icon: 'alert-triangle',
    stepByStep: [
      'Liste as etapas do processo ou funções do produto',
      'Para cada etapa, identifique modos de falha potenciais',
      'Para cada falha, descreva o efeito no cliente/processo',
      'Avalie Severidade (S): 1–10 (1=sem impacto, 10=crítico)',
      'Identifique causas e avalie Ocorrência (O): 1–10',
      'Identifique controles atuais e avalie Detecção (D): 1–10 (10=indetectável)',
      'Calcule RPN = S × O × D',
      'Priorize itens com RPN > 100 ou S ≥ 8',
      'Defina ações corretivas e responsáveis',
    ],
    commonErrors: [
      'Avaliar Detecção inversamente — 10 = muito difícil de detectar',
      'Subestimar a Severidade por otimismo',
      'Não atualizar o FMEA após implementar ações',
    ],
    bestPractices: [
      'Equipe multifuncional: qualidade, engenharia, produção',
      'Atualize periodicamente — FMEA é documento vivo',
      'Foque em S × O quando a detecção não é controlável',
    ],
    exampleContext: 'Processo: Montagem de PCB. Falha: Solda fria. Efeito: Produto não funciona (S=9). Causa: Temperatura do forno incorreta (O=4). Controle: Inspeção visual (D=7). RPN = 9×4×7 = 252. Ação: Instalar sensor de temperatura com alarme.',
  },

  // PLAN Phase — remaining tools (abbreviated metadata)
  VOC: {
    name: 'VOC — Voz do Cliente',
    phase: 'PLAN',
    description: 'Captura e tradução dos requisitos e expectativas dos clientes.',
    objective: 'Entender o que o cliente realmente valoriza e traduzir em requisitos mensuráveis.',
    whenToUse: ['Início de projetos com foco no cliente', 'Antes de definir CTQs'],
    whenToAvoid: ['Projetos puramente internos sem impacto no cliente final'],
    benefits: ['Alinha esforços de melhoria com necessidades reais do cliente', 'Previne melhorias que não geram valor'],
    estimatedDuration: '1–3 horas',
    difficulty: 'intermediate',
    relatedTools: ['CTQ', 'KANO', 'SIPOC'],
    icon: 'mic',
    stepByStep: ['Identifique os clientes', 'Colete feedbacks (entrevistas, pesquisas, reclamações)', 'Categorize as necessidades', 'Priorize por impacto', 'Traduza em requisitos mensuráveis (CTQ)'],
    commonErrors: ['Assumir que você sabe o que o cliente quer', 'Amostras muito pequenas'],
    bestPractices: ['Combine métodos qualitativos e quantitativos', 'Inclua clientes insatisfeitos'],
    exampleContext: 'Pesquisa com 50 clientes revelou: "entrega no prazo" é o requisito #1 (92% mencionaram).',
  },
  CTQ: {
    name: 'CTQ — Crítico para Qualidade',
    phase: 'PLAN',
    description: 'Características críticas do produto/serviço que impactam diretamente a satisfação do cliente.',
    objective: 'Traduzir necessidades do cliente em especificações mensuráveis e controláveis.',
    whenToUse: ['Após VOC', 'Para definir KPIs do projeto'],
    whenToAvoid: ['Sem dados de VOC'],
    benefits: ['Foco nos atributos que realmente importam', 'Base para definição de KPIs'],
    estimatedDuration: '45–60 min',
    difficulty: 'intermediate',
    relatedTools: ['VOC', 'KPI_DASHBOARD'],
    icon: 'target',
    stepByStep: ['Liste as necessidades do cliente (VOC)', 'Para cada necessidade, defina o CTQ mensurável', 'Defina a especificação (limite superior/inferior)', 'Valide com o cliente'],
    commonErrors: ['CTQs muito amplos sem especificação', 'Especificações sem base em dados'],
    bestPractices: ['Cada CTQ deve ter uma unidade de medida clara', 'Valide a especificação com dados históricos'],
    exampleContext: 'Necessidade: "entrega rápida" → CTQ: Lead time de entrega ≤ 2 dias úteis.',
  },
  PROJECT_CHARTER: {
    name: 'Project Charter',
    phase: 'PLAN',
    description: 'Documento de autorização formal do projeto com escopo, objetivos e recursos.',
    objective: 'Formalizar o projeto, alinhar expectativas e obter aprovação da liderança.',
    whenToUse: ['Início de todo projeto PDCA/DMAIC', 'Para projetos com impacto financeiro relevante'],
    whenToAvoid: ['Melhorias rápidas (kaizen) de baixo impacto'],
    benefits: ['Alinhamento com patrocinador', 'Autorização formal de recursos', 'Referência durante o projeto'],
    estimatedDuration: '1–2 horas',
    difficulty: 'beginner',
    relatedTools: ['SIPOC', 'SWOT'],
    icon: 'file-text',
    stepByStep: ['Descreva o problema (business case)', 'Defina o objetivo e meta mensurável', 'Defina o escopo (in/out)', 'Identifique a equipe e sponsor', 'Defina milestones', 'Estime impacto financeiro', 'Obtenha assinaturas'],
    commonErrors: ['Escopo muito amplo', 'Meta vaga sem número', 'Sem aprovação formal do sponsor'],
    bestPractices: ['Seja específico na meta: "reduzir de X para Y até Z"', 'Revise o charter se o escopo mudar'],
    exampleContext: 'Projeto: Redução de lead time. Meta: Reduzir de 5 para 2 dias em 90 dias. Impacto: R$ 500K/ano em satisfação de cliente.',
  },
  FLOWCHART: {
    name: 'Fluxograma',
    phase: 'PLAN',
    description: 'Representação visual das etapas, decisões e fluxos de um processo.',
    objective: 'Documentar e comunicar o estado atual (As-Is) ou futuro (To-Be) de um processo.',
    whenToUse: ['Antes de otimizar um processo', 'Para treinar novos colaboradores', 'Para identificar atividades que não agregam valor'],
    whenToAvoid: ['Processos extremamente complexos com centenas de etapas — use VSM'],
    benefits: ['Visibilidade do processo', 'Identificação de desperdícios e gargalos', 'Base para padronização (SOP)'],
    estimatedDuration: '1–2 horas',
    difficulty: 'beginner',
    relatedTools: ['VSM', 'SIPOC', 'PROCESS_MAP'],
    icon: 'git-merge',
    stepByStep: ['Defina início e fim do processo', 'Liste todas as atividades em sequência', 'Identifique pontos de decisão (diamantes)', 'Conecte com setas', 'Valide com quem executa', 'Identifique desperdícios (atividades sem valor)'],
    commonErrors: ['Nível de detalhe inconsistente', 'Não incluir pontos de decisão', 'Não validar com o time operacional'],
    bestPractices: ['Use swimlanes para mostrar responsáveis por etapa', 'Mapeie o estado atual antes de propor melhorias'],
    exampleContext: 'Processo de aprovação de compras: Solicitação → Validação técnica (decisão: aprovado?) → Se sim: emissão de PO → Envio ao fornecedor.',
  },
  VSM: {
    name: 'VSM — Mapa do Fluxo de Valor',
    phase: 'PLAN',
    description: 'Ferramenta Lean para mapear todo o fluxo de material e informação, identificando desperdícios.',
    objective: 'Visualizar o fluxo completo de valor e identificar onde tempo/recursos são desperdiçados.',
    whenToUse: ['Projetos Lean em manufatura ou serviços', 'Quando o lead time total é muito maior que o tempo de processamento', 'Para projetar o estado futuro do processo'],
    whenToAvoid: ['Processos únicos e não repetitivos', 'Projetos sem foco em fluxo e lead time'],
    benefits: ['Identifica desperdícios no fluxo completo', 'Visualiza relação entre lead time e tempo de valor', 'Base para o estado futuro Lean'],
    estimatedDuration: '2–4 horas',
    difficulty: 'advanced',
    relatedTools: ['FLOWCHART', 'SIPOC'],
    icon: 'map',
    stepByStep: ['Selecione a família de produto/serviço', 'Mapeie o estado atual: cliente → processos → fornecedor', 'Adicione dados: tempo de ciclo, WIP, lead time', 'Calcule eficiência do fluxo (valor/lead time)', 'Identifique desperdícios e muda', 'Projete o estado futuro', 'Crie plano de implementação'],
    commonErrors: ['Pular o estado atual e ir direto ao futuro', 'Dados incorretos de tempo de ciclo', 'Esquecer o fluxo de informação'],
    bestPractices: ['Caminhe o processo (gemba walk) antes de mapear', 'Use ícones VSM padronizados', 'Calcule eficiência do fluxo: VA/Lead Time'],
    exampleContext: 'Montagem de produto: Lead time total = 5 dias, tempo de valor adicionado = 4 horas. Eficiência = 10%. Maior espera identificada: aguardar aprovação de qualidade (2 dias).',
  },
  BENCHMARKING: {
    name: 'Benchmarking',
    phase: 'PLAN',
    description: 'Comparação sistemática de desempenho com referências internas ou melhores práticas do setor.',
    objective: 'Definir metas realistas e identificar boas práticas a adotar.',
    whenToUse: ['Para definir metas com base em referências externas', 'Quando a equipe não sabe qual performance é possível alcançar'],
    whenToAvoid: ['Quando as referências externas não são comparáveis', 'Sem dados confiáveis de benchmark'],
    benefits: ['Metas baseadas em realidade do mercado', 'Identifica gap competitivo', 'Fonte de inspiração para soluções'],
    estimatedDuration: '2–8 horas (pesquisa)',
    difficulty: 'intermediate',
    relatedTools: ['CTQ', 'KPI_DASHBOARD'],
    icon: 'trending-up',
    stepByStep: ['Defina o processo ou KPI a comparar', 'Identifique benchmarks internos (outras unidades) e externos (setor)', 'Colete dados de desempenho', 'Compare e calcule o gap', 'Identifique práticas que explicam a diferença', 'Adapte e incorpore as melhores práticas'],
    commonErrors: ['Comparar processos não comparáveis', 'Copiar práticas sem adaptar ao contexto', 'Focar só nos números sem entender as causas'],
    bestPractices: ['Comece por benchmarks internos — mais fáceis de obter', 'Use associações setoriais como fonte de dados', 'Benchmarking é aprendizado, não cópia'],
    exampleContext: 'Lead time de entrega: empresa = 5 dias, melhor do setor = 1,5 dias. Gap = 3,5 dias. Prática identificada: cross-docking e automação de separação.',
  },
  KANO: {
    name: 'Modelo de Kano',
    phase: 'PLAN',
    description: 'Classifica atributos do produto/serviço em: básicos, performance e encantadores.',
    objective: 'Priorizar funcionalidades e melhorias pelo impacto na satisfação do cliente.',
    whenToUse: ['Desenvolvimento de novos produtos/serviços', 'Priorização de backlog com foco no cliente'],
    whenToAvoid: ['Sem capacidade de pesquisa com clientes', 'Projetos puramente internos'],
    benefits: ['Priorização centrada no cliente', 'Identifica diferenciadores competitivos', 'Evita investir em atributos de baixo impacto'],
    estimatedDuration: '2–4 horas (incluindo pesquisa)',
    difficulty: 'intermediate',
    relatedTools: ['VOC', 'CTQ'],
    icon: 'smile',
    stepByStep: ['Identifique atributos a avaliar', 'Aplique questionário Kano (funcional + disfuncional)', 'Classifique: Básico (B), Performance (P), Encantador (E)', 'Priorize: garanta B, maximize P, invista em E selecionados', 'Documente o mapa de satisfação'],
    commonErrors: ['Não aplicar a pergunta disfuncional', 'Amostras muito pequenas', 'Ignorar atributos básicos (causam insatisfação se ausentes)'],
    bestPractices: ['Mínimo 30 respondentes por segmento', 'Reavalie periodicamente — encantadores viram básicos com o tempo'],
    exampleContext: 'App de rastreamento de entrega: Básico (notificação de atraso), Performance (atualização em tempo real), Encantador (previsão de entrega com IA).',
  },
  BRAINSTORMING: {
    name: 'Brainstorming',
    phase: 'PLAN',
    description: 'Técnica de geração de ideias em grupo sem julgamento inicial.',
    objective: 'Gerar grande volume de ideias ou causas potenciais em tempo curto.',
    whenToUse: ['Fase inicial de análise de causas', 'Geração de soluções criativas', 'Quando a equipe está "presa" nas ideias habituais'],
    whenToAvoid: ['Quando a causa raiz já é conhecida', 'Grupos muito hierarquizados sem psicologia segura'],
    benefits: ['Diversidade de perspectivas', 'Quebra de paradigmas', 'Engajamento da equipe'],
    estimatedDuration: '30–60 min',
    difficulty: 'beginner',
    relatedTools: ['ISHIKAWA', 'FIVE_WHYS'],
    icon: 'lightbulb',
    stepByStep: ['Defina o tema claramente', 'Regras: sem julgamento, quantidade antes de qualidade', 'Fase divergente: geração livre de ideias (15 min)', 'Consolidação: eliminar duplicatas, agrupar', 'Fase convergente: votação e priorização', 'Selecione as ideias mais promissoras'],
    commonErrors: ['Avaliar ideias durante a geração', 'Permitir que uma pessoa domine', 'Encerrar na lista — não priorizar'],
    bestPractices: ['Use post-its ou ferramentas digitais para anonimato', 'Inclua pessoas de fora do processo para perspectiva externa', 'Combine com Ishikawa para estruturar as ideias'],
    exampleContext: '20 causas geradas em 15 min sobre atraso de entregas. Após consolidação: 8 causas únicas. Após votação: top 3 para análise mais profunda.',
  },
  CAUSE_EFFECT_MATRIX: {
    name: 'Matriz Causa-Efeito',
    phase: 'PLAN',
    description: 'Matriz que correlaciona causas (entradas do processo) com efeitos (saídas — CTQs).',
    objective: 'Priorizar as variáveis de entrada que mais impactam as saídas críticas.',
    whenToUse: ['Após Brainstorming ou Ishikawa', 'Para priorizar variáveis antes do FMEA', 'Projetos Six Sigma na fase Analyze'],
    whenToAvoid: ['Menos de 5 causas e 3 efeitos — simplificação desnecessária'],
    benefits: ['Priorização quantitativa de causas', 'Conexão explícita entre causas e CTQs', 'Foco nos poucos fatores de maior impacto'],
    estimatedDuration: '1–2 horas',
    difficulty: 'intermediate',
    relatedTools: ['ISHIKAWA', 'FMEA', 'PARETO'],
    icon: 'table',
    stepByStep: ['Liste os CTQs (saídas) nas colunas', 'Pondere os CTQs por importância (1–10)', 'Liste as causas potenciais nas linhas', 'Avalie correlação de cada causa × CTQ (0, 1, 3, 9)', 'Calcule score: Σ(correlação × peso do CTQ)', 'Ordene causas por score — priorize as de maior score'],
    commonErrors: ['Não ponderar os CTQs', 'Usar escala linear (1–10) em vez de 0/1/3/9', 'Lista de causas muito extensa sem filtragem prévia'],
    bestPractices: ['Limite a 15–20 causas e 5–7 CTQs', 'Envolva engenharia de processo e qualidade', 'As causas de alto score são candidatas ao FMEA'],
    exampleContext: 'CTQs: Lead time (peso 9), Defeitos (peso 8). Causa "temperatura de processo" tem correlação 9 com defeitos e 3 com lead time. Score = 9×8 + 3×9 = 99. Prioridade alta.',
  },
  PROCESS_MAP: {
    name: 'Mapa de Processo',
    phase: 'PLAN',
    description: 'Representação detalhada com swimlanes, inputs/outputs e responsáveis por etapa.',
    objective: 'Documentar o processo em nível operacional para análise e padronização.',
    whenToUse: ['Antes de redesenhar um processo', 'Para criar procedimentos operacionais', 'Análise de responsabilidades e handoffs'],
    whenToAvoid: ['Visão de alto nível — use SIPOC ou Fluxograma'],
    benefits: ['Clareza de responsabilidades', 'Identificação de handoffs problemáticos', 'Base para SOPs'],
    estimatedDuration: '2–3 horas',
    difficulty: 'intermediate',
    relatedTools: ['FLOWCHART', 'SIPOC', 'SOP'],
    icon: 'layers',
    stepByStep: ['Defina os swimlanes (funções/departamentos)', 'Mapeie cada atividade no swimlane correto', 'Identifique inputs e outputs de cada atividade', 'Marque pontos de decisão e aprovação', 'Identifique sistemas/ferramentas usados', 'Valide com todos os responsáveis'],
    commonErrors: ['Swimlanes por pessoa em vez de função', 'Nível de detalhe inconsistente entre etapas'],
    bestPractices: ['Caminhe o processo antes de mapear', 'Use verbos de ação nos nomes das atividades'],
    exampleContext: 'Processo de onboarding: RH (cadastro) → TI (acesso sistemas) → Gestor (apresentação equipe) → Treinamento (capacitação). Handoff crítico: TI demora 3 dias para liberar acessos.',
  },

  // DO Phase tools
  KANBAN: {
    name: 'Kanban',
    phase: 'DO',
    description: 'Sistema visual de gestão de tarefas com colunas representando estados do fluxo.',
    objective: 'Visualizar e gerenciar o fluxo de trabalho, limitando o WIP para aumentar throughput.',
    whenToUse: ['Gestão de tarefas do plano de ação', 'Trabalho contínuo e repetitivo', 'Equipes ágeis'],
    whenToAvoid: ['Projetos com sequência rígida e dependências complexas — use Gantt'],
    benefits: ['Visibilidade do status em tempo real', 'Identificação de gargalos', 'Redução de WIP e lead time'],
    estimatedDuration: 'Contínuo',
    difficulty: 'beginner',
    relatedTools: ['ACTION_PLAN', 'CHECKLIST'],
    icon: 'layout-dashboard',
    stepByStep: ['Defina as colunas (Backlog, Em progresso, Revisão, Concluído)', 'Adicione cartões para cada tarefa', 'Limite WIP por coluna', 'Realize reuniões diárias (stand-up)', 'Monitore lead time e throughput', 'Melhore continuamente o fluxo'],
    commonErrors: ['Sem limite de WIP', 'Cartões sem responsável e prazo', 'Board desatualizado'],
    bestPractices: ['Atualize o board diariamente', 'Limite WIP: 2–3 itens por pessoa', 'Use classes de serviço para urgências'],
    exampleContext: 'Plano de ação com 15 tarefas. WIP limitado a 3 por coluna. Throughput médio: 2 tarefas/dia. Lead time médio: 4 dias por tarefa.',
  },
  ACTION_PLAN: {
    name: 'Plano de Ação',
    phase: 'DO',
    description: 'Lista estruturada de ações com responsável, prazo, status e recursos necessários.',
    objective: 'Garantir que todas as ações de melhoria sejam executadas com clareza e rastreabilidade.',
    whenToUse: ['Após identificar soluções', 'Para acompanhar a execução do projeto'],
    whenToAvoid: ['Substituir por kanban quando o fluxo é mais importante que a lista'],
    benefits: ['Rastreabilidade de ações', 'Clareza de responsabilidades', 'Base para reuniões de acompanhamento'],
    estimatedDuration: 'Contínuo',
    difficulty: 'beginner',
    relatedTools: ['KANBAN', 'FIVE_W2H'],
    icon: 'check-square',
    stepByStep: ['Liste todas as ações necessárias', 'Atribua responsável único por ação', 'Defina prazo específico', 'Estime CAPEX/OPEX se necessário', 'Acompanhe status semanalmente', 'Documente evidências de conclusão'],
    commonErrors: ['Ações sem responsável', 'Prazos vagos', 'Sem reunião de acompanhamento'],
    bestPractices: ['Uma ação = um responsável', 'Reunião semanal de 30 min de acompanhamento', 'Documente impedimentos imediatamente'],
    exampleContext: 'Plano de redução de lead time: 12 ações, 4 responsáveis, prazo 90 dias. Reunião semanal às terças-feiras.',
  },
  CHECKLIST: {
    name: 'Checklist',
    phase: 'DO',
    description: 'Lista de verificação de itens obrigatórios para uma tarefa ou processo.',
    objective: 'Garantir que etapas críticas não sejam esquecidas na execução.',
    whenToUse: ['Processos com etapas críticas e sequenciais', 'Auditorias e inspeções', 'Treinamento de novos colaboradores'],
    whenToAvoid: ['Processos simples que a equipe executa de memória sem falhas'],
    benefits: ['Redução de erros humanos', 'Padronização da execução', 'Rastreabilidade de conformidade'],
    estimatedDuration: '15–30 min para criar',
    difficulty: 'beginner',
    relatedTools: ['ACTION_PLAN', 'AUDIT'],
    icon: 'list',
    stepByStep: ['Liste todas as etapas críticas do processo', 'Ordene logicamente', 'Para cada item: defina critério de aceite', 'Valide com quem executa', 'Implemente e ajuste conforme necessário'],
    commonErrors: ['Checklists longos demais (>20 itens) — dividir em seções', 'Itens ambíguos sem critério claro', 'Não atualizar conforme o processo muda'],
    bestPractices: ['Máximo 10 itens por seção', 'Linguagem simples e direta', 'Revise periodicamente'],
    exampleContext: 'Checklist de expedição: □ Conferir NF □ Conferir volumes □ Fotografar carga □ Obter assinatura do transportador □ Lançar no sistema.',
  },

  // CHECK Phase tools
  KPI_DASHBOARD: {
    name: 'Dashboard de KPIs',
    phase: 'CHECK',
    description: 'Painel visual com indicadores de desempenho do projeto, comparando baseline, meta e atual.',
    objective: 'Monitorar o progresso do projeto com dados em tempo real.',
    whenToUse: ['Durante toda a fase Check', 'Para comunicar resultados à liderança'],
    whenToAvoid: ['Sem dados suficientes para calcular os indicadores'],
    benefits: ['Visibilidade do progresso', 'Tomada de decisão baseada em dados', 'Alinhamento de stakeholders'],
    estimatedDuration: 'Contínuo',
    difficulty: 'intermediate',
    relatedTools: ['SPC_CHART', 'RUN_CHART', 'BEFORE_AFTER'],
    icon: 'activity',
    stepByStep: ['Defina KPIs alinhados aos objetivos do projeto', 'Estabeleça baseline (situação atual)', 'Defina meta e prazo', 'Colete medições periodicamente', 'Visualize tendências', 'Tome ações corretivas quando necessário'],
    commonErrors: ['KPIs sem baseline definido', 'Medir sem agir nos desvios', 'Excesso de KPIs — foque nos críticos'],
    bestPractices: ['Máximo 5–7 KPIs por projeto', 'Frequência de medição adequada ao processo', 'Mostre tendência, não só o valor atual'],
    exampleContext: 'KPIs: Lead time (baseline 5d, meta 2d, atual 3,2d — progresso 64%), Taxa de defeitos (baseline 8%, meta 2%, atual 3,5% — progresso 77%).',
  },
  SPC_CHART: {
    name: 'Gráfico CEP/SPC',
    phase: 'CHECK',
    description: 'Controle Estatístico de Processo com limites de controle UCL/LCL e detecção de causas especiais.',
    objective: 'Distinguir variação natural do processo de causas especiais que requerem ação.',
    whenToUse: ['Processos com medições contínuas', 'Monitoramento pós-implementação de melhorias', 'Controle de qualidade em produção'],
    whenToAvoid: ['Menos de 20–25 pontos de dados', 'Dados não numéricos contínuos'],
    benefits: ['Distingue variação normal de anormal', 'Previne superajuste do processo', 'Detecta problemas antes de reclamações'],
    estimatedDuration: '1–2 horas (setup)',
    difficulty: 'advanced',
    relatedTools: ['RUN_CHART', 'HISTOGRAM', 'KPI_DASHBOARD'],
    icon: 'trending-up',
    stepByStep: ['Colete mínimo 20–25 medições', 'Calcule média (x̄) e desvio padrão (σ)', 'Calcule UCL = x̄ + 3σ e LCL = x̄ - 3σ', 'Plote os dados com as linhas de controle', 'Identifique causas especiais (pontos fora dos limites, 8 pontos consecutivos de um lado)', 'Investigue e elimine causas especiais'],
    commonErrors: ['Recalcular limites com causas especiais incluídas', 'Confundir limites de controle com especificação', 'Reagir a cada ponto fora da média (overcontrol)'],
    bestPractices: ['Baseie limites no processo estável (sem causas especiais)', 'Use regras de Western Electric para detectar padrões', 'Separe gráficos por turno/máquina se há estratificação'],
    exampleContext: 'Lead time diário: x̄ = 3,2 dias, σ = 0,8 dias. UCL = 5,6 dias, LCL = 0,8 dias. Dia 15 registrou 6,1 dias — causa especial investigada: falta de motorista.',
  },
  HISTOGRAM: {
    name: 'Histograma',
    phase: 'CHECK',
    description: 'Gráfico de distribuição de frequências para visualizar o comportamento de uma variável.',
    objective: 'Entender a distribuição e variabilidade dos dados do processo.',
    whenToUse: ['Análise da distribuição de um KPI', 'Verificação de normalidade', 'Antes de calcular SPC'],
    whenToAvoid: ['Menos de 30 pontos de dados', 'Dados categóricos — use Pareto'],
    benefits: ['Revela a forma da distribuição', 'Identifica se o processo é centrado na meta', 'Detecta bimodalidade (dois processos misturados)'],
    estimatedDuration: '30–45 min',
    difficulty: 'intermediate',
    relatedTools: ['SPC_CHART', 'BEFORE_AFTER'],
    icon: 'bar-chart',
    stepByStep: ['Colete dados (mínimo 30 pontos)', 'Calcule número de classes (√n arredondado)', 'Defina amplitude das classes', 'Conte frequência em cada classe', 'Plote o gráfico', 'Analise a forma (normal, assimétrica, bimodal)'],
    commonErrors: ['Poucas classes (perde informação) ou muitas (ruído)', 'Não adicionar linhas de especificação ao gráfico'],
    bestPractices: ['Use Sturges: k = 1 + 3,322 × log(n)', 'Adicione linhas de limite inferior/superior de especificação', 'Compare antes/depois da melhoria'],
    exampleContext: 'Lead time (n=100): distribuição normal centrada em 3,2 dias. Especificação: ≤ 2 dias. 28% dos dados fora da especificação. Após melhoria: centrado em 1,8 dias, 5% fora.',
  },
  RUN_CHART: {
    name: 'Run Chart',
    phase: 'CHECK',
    description: 'Gráfico de tendência temporal simples para visualizar evolução de um KPI ao longo do tempo.',
    objective: 'Identificar tendências, ciclos e mudanças de nível no processo ao longo do tempo.',
    whenToUse: ['Monitoramento contínuo de KPI', 'Antes de ter dados suficientes para SPC', 'Comunicação de resultados à liderança'],
    whenToAvoid: ['Quando você precisa de limites estatísticos — use SPC'],
    benefits: ['Simples e de fácil interpretação', 'Mostra evolução temporal claramente', 'Identifica tendências antes do SPC'],
    estimatedDuration: '15–30 min',
    difficulty: 'beginner',
    relatedTools: ['SPC_CHART', 'KPI_DASHBOARD'],
    icon: 'line-chart',
    stepByStep: ['Defina o KPI e frequência de medição', 'Colete medições em sequência temporal', 'Plote os pontos com linha de tendência', 'Adicione linha da média', 'Identifique padrões: tendência, ciclo, salto de nível', 'Marque eventos importantes no eixo temporal'],
    commonErrors: ['Escala do eixo Y que distorce a percepção', 'Não marcar eventos relevantes (mudanças, implementações)'],
    bestPractices: ['Inclua linha da meta', 'Marque a data de implementação das melhorias', 'Use escala que inclua zero para contexto'],
    exampleContext: 'Lead time semanal: semanas 1–8 (pré-melhoria): média 5,1 dias. Semana 9: implementação de novo processo. Semanas 10–18: média 2,8 dias. Tendência de redução confirmada.',
  },
  BEFORE_AFTER: {
    name: 'Análise Before vs. After',
    phase: 'CHECK',
    description: 'Comparação estatística e visual dos resultados antes e depois da implementação das melhorias.',
    objective: 'Quantificar e comunicar o impacto das melhorias implementadas.',
    whenToUse: ['Após implementar melhorias', 'Para comprovar resultados à liderança', 'Para calcular ROI e savings'],
    whenToAvoid: ['Sem dados suficientes do período pré-melhoria'],
    benefits: ['Comprova o impacto das melhorias com dados', 'Base para cálculo de ROI', 'Comunicação clara de resultados'],
    estimatedDuration: '1–2 horas',
    difficulty: 'intermediate',
    relatedTools: ['KPI_DASHBOARD', 'HISTOGRAM', 'RUN_CHART'],
    icon: 'git-compare',
    stepByStep: ['Colete dados do período antes (baseline)', 'Colete dados do período após a melhoria', 'Compare médias, desvio padrão e distribuição', 'Teste significância estatística (t-test se aplicável)', 'Calcule impacto financeiro', 'Documente e comunique os resultados'],
    commonErrors: ['Períodos de comparação muito curtos', 'Não controlar variáveis externas (sazonalidade)', 'Comparar médias sem verificar variabilidade'],
    bestPractices: ['Mínimo 30 pontos em cada período', 'Considere sazonalidade na análise', 'Mostre tanto a média quanto a variabilidade'],
    exampleContext: 'Lead time: Antes (n=60): média 5,1d, σ=1,2d. Depois (n=60): média 2,3d, σ=0,6d. Redução de 55% na média e 50% na variabilidade. Saving estimado: R$ 450K/ano.',
  },

  // ACT Phase tools
  STANDARDIZATION: {
    name: 'Padronização',
    phase: 'ACT',
    description: 'Formalização do novo processo em padrões documentados para garantir a sustentabilidade das melhorias.',
    objective: 'Sustentar os ganhos obtidos prevenindo retorno ao estado anterior.',
    whenToUse: ['Após comprovação dos resultados na fase Check', 'Sempre que uma melhoria é validada'],
    whenToAvoid: ['Antes de confirmar que a melhoria é sustentável'],
    benefits: ['Sustentabilidade das melhorias', 'Facilita treinamento de novos colaboradores', 'Reduz dependência de pessoas-chave'],
    estimatedDuration: '2–4 horas',
    difficulty: 'beginner',
    relatedTools: ['SOP', 'TRAINING', 'AUDIT'],
    icon: 'bookmark',
    stepByStep: ['Documente o novo processo no SOP', 'Atualize fluxogramas e instruções de trabalho', 'Treine toda a equipe no novo padrão', 'Atualize sistemas e ferramentas', 'Defina indicadores de monitoramento', 'Estabeleça plano de auditoria'],
    commonErrors: ['Documentar sem treinar a equipe', 'SOPs complexos demais que ninguém lê', 'Não atualizar documentos quando o processo muda'],
    bestPractices: ['SOPs com imagens e exemplos visuais', 'Treinamento prático, não apenas teórico', 'Auditorias nos primeiros 30–60 dias após implementação'],
    exampleContext: 'Novo processo de separação de pedidos documentado em SOP v2.0. Treinamento realizado com 12 operadores. Auditoria agendada para 30 dias.',
  },
  AUDIT: {
    name: 'Auditoria de Processo',
    phase: 'ACT',
    description: 'Verificação periódica da conformidade do processo com os padrões estabelecidos.',
    objective: 'Garantir que as melhorias implementadas estejam sendo mantidas.',
    whenToUse: ['30, 60 e 90 dias após implementação', 'Periodicamente para sustentação'],
    whenToAvoid: ['Antes de existirem padrões documentados'],
    benefits: ['Detecta desvios antes de retorno ao estado anterior', 'Reforça a cultura de conformidade', 'Identifica oportunidades de melhoria'],
    estimatedDuration: '1–2 horas por auditoria',
    difficulty: 'beginner',
    relatedTools: ['STANDARDIZATION', 'CHECKLIST', 'SOP'],
    icon: 'search',
    stepByStep: ['Prepare o checklist de auditoria baseado no SOP', 'Realize a auditoria no local (gemba)', 'Documente conformidades e não-conformidades', 'Classifique por severidade', 'Emita relatório e plano de ação', 'Acompanhe o fechamento das não-conformidades'],
    commonErrors: ['Auditorias apenas documentais (sem gemba)', 'Sem plano de ação para não-conformidades', 'Frequência muito baixa nos primeiros meses'],
    bestPractices: ['Auditoria surpresa vs. programada — use ambas', 'Foco em aprendizado, não punição', 'Compartilhe resultados com a equipe'],
    exampleContext: 'Auditoria 30 dias: 18/20 itens conformes. 2 não-conformidades: operador desconhece novo procedimento de conferência. Ação: retraining imediato.',
  },
  LESSONS_LEARNED: {
    name: 'Lições Aprendidas',
    phase: 'ACT',
    description: 'Documentação estruturada dos aprendizados do projeto para aplicação em projetos futuros.',
    objective: 'Capturar e compartilhar o conhecimento gerado no projeto para evitar repetição de erros.',
    whenToUse: ['Encerramento de todo projeto', 'Ao longo do projeto em marcos importantes'],
    whenToAvoid: ['Raramente — sempre deve ser feito'],
    benefits: ['Acelera futuros projetos', 'Evita repetição de erros', 'Constrói base de conhecimento organizacional'],
    estimatedDuration: '1–2 horas',
    difficulty: 'beginner',
    relatedTools: ['STANDARDIZATION', 'SOP'],
    icon: 'book-open',
    stepByStep: ['Reúna a equipe para retrospectiva', 'O que funcionou bem? (manter)', 'O que não funcionou? (evitar)', 'O que faríamos diferente? (melhorar)', 'Documente com contexto suficiente', 'Compartilhe no banco de conhecimento'],
    commonErrors: ['Lições vagas sem contexto', 'Não compartilhar com outros times', 'Fazer apenas no encerramento — faça também em marcos intermediários'],
    bestPractices: ['Seja específico: descreva o contexto, o erro e a lição', 'Categorize por tipo: técnica, processo, pessoas, ferramentas', 'Indexe para facilitar busca futura'],
    exampleContext: 'Lição: "Não subestime o tempo de treinamento. Planejamos 4 horas, precisamos de 12 para garantir proficiência. Inclua sempre tempo de prática nos planos futuros."',
  },
  SOP: {
    name: 'SOP — Procedimento Operacional Padrão',
    phase: 'ACT',
    description: 'Documento que descreve passo a passo como executar um processo de forma padronizada.',
    objective: 'Garantir que o processo seja executado consistentemente, independente de quem o executa.',
    whenToUse: ['Para qualquer processo repetitivo e crítico', 'Após implementação de melhorias validadas'],
    whenToAvoid: ['Processos únicos e não repetitivos'],
    benefits: ['Consistência na execução', 'Facilita treinamento', 'Reduz dependência de pessoas-chave', 'Base para auditoria'],
    estimatedDuration: '2–4 horas por SOP',
    difficulty: 'beginner',
    relatedTools: ['STANDARDIZATION', 'TRAINING', 'AUDIT'],
    icon: 'file-check',
    stepByStep: ['Defina o processo, escopo e responsável', 'Liste materiais/ferramentas necessários', 'Descreva cada etapa com nível de detalhe adequado', 'Adicione fotos/diagramas nas etapas críticas', 'Defina critérios de qualidade por etapa', 'Revise com quem executa o processo', 'Obtenha aprovação formal e controle de versão'],
    commonErrors: ['SOPs de 20+ páginas que ninguém lê', 'Sem imagens ou referências visuais', 'Versões desatualizadas em circulação'],
    bestPractices: ['1 página por processo simples, máximo 5 para complexos', 'Use linguagem simples e direta', 'Controle de versão com data e aprovador', 'Disponibilize no local de trabalho'],
    exampleContext: 'SOP v2.0 — Separação de Pedidos. 3 páginas. Inclui fotos do scanner, critério de conferência e fluxo de exceção. Aprovado por Gerente de Logística em 15/03/2024.',
  },
  TRAINING: {
    name: 'Gestão de Treinamentos',
    phase: 'ACT',
    description: 'Planejamento e controle dos treinamentos necessários para sustentar as melhorias.',
    objective: 'Garantir que toda a equipe tenha o conhecimento necessário para manter o novo processo.',
    whenToUse: ['Após implementação de melhorias', 'Sempre que o processo é alterado', 'Onboarding de novos colaboradores'],
    whenToAvoid: ['Raramente — capacitação é sempre relevante'],
    benefits: ['Sustentabilidade das melhorias', 'Redução de erros por falta de conhecimento', 'Desenvolvimento da equipe'],
    estimatedDuration: 'Variável por treinamento',
    difficulty: 'beginner',
    relatedTools: ['SOP', 'STANDARDIZATION', 'AUDIT'],
    icon: 'graduation-cap',
    stepByStep: ['Identifique lacunas de competência (análise de necessidades)', 'Defina conteúdo e formato do treinamento', 'Selecione instrutor e local', 'Execute o treinamento com prática', 'Avalie eficácia (antes/depois)', 'Documente participantes e resultado', 'Planeje reforço e reciclagem'],
    commonErrors: ['Treinamento apenas teórico sem prática', 'Sem avaliação de eficácia', 'Não treinar substitutos'],
    bestPractices: ['70% prática, 30% teoria', 'Certifique proficiência antes de liberar para o processo', 'Treinamento OJT (on the job) é mais eficaz que sala de aula'],
    exampleContext: 'Treinamento novo SOP de separação: 12 operadores, 4 horas, 2 turmas. Avaliação: 95% aprovados no teste prático. Retraining planejado em 90 dias.',
  },
};

export const PHASE_TOOLS: Record<PhaseType, ToolType[]> = {
  PLAN: ['SIPOC', 'VOC', 'CTQ', 'PROJECT_CHARTER', 'SWOT', 'GUT', 'PARETO', 'ISHIKAWA', 'FIVE_WHYS', 'FLOWCHART', 'VSM', 'FIVE_W2H', 'BENCHMARKING', 'KANO', 'FMEA', 'BRAINSTORMING', 'CAUSE_EFFECT_MATRIX', 'PROCESS_MAP'],
  DO: ['KANBAN', 'ACTION_PLAN', 'CHECKLIST'],
  CHECK: ['KPI_DASHBOARD', 'SPC_CHART', 'HISTOGRAM', 'RUN_CHART', 'BEFORE_AFTER'],
  ACT: ['STANDARDIZATION', 'AUDIT', 'LESSONS_LEARNED', 'SOP', 'TRAINING'],
};

export const TOOL_AI_RECOMMENDATIONS: Record<string, ToolType[]> = {
  'atraso logístico': ['PARETO', 'ISHIKAWA', 'FIVE_WHYS', 'VSM'],
  'problema financeiro': ['PARETO', 'SWOT', 'GUT'],
  'problema operacional': ['VSM', 'FLOWCHART', 'SIPOC'],
  'retrabalho defeito': ['FMEA', 'ISHIKAWA', 'SPC_CHART'],
  'atendimento cliente': ['VOC', 'CTQ', 'KANO'],
  'processo novo': ['SIPOC', 'FLOWCHART', 'PROJECT_CHARTER'],
};
